name: Feature request
description: Proponha uma evolução para o framework
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual necessidade esta proposta resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solução proposta
    validations:
      required: true
